# Generated by Django 6.0.3 on 2026-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="ID чата в Telegram для отправки уведомлений",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
