# Generated by Django 6.0.3 on 2026-04-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
